import React from 'react';
import { Box, ArrowLeft, Mail, Phone } from 'lucide-react';

const email = 'zhujiawen519@gmail.com';
const links = [['/privacy', 'Privacy'], ['/terms', 'Terms'], ['/policy', 'Usage & billing'], ['/contact', 'Contact'], ['/delete-account', 'Data deletion']];
export const LegalFooter = () => <footer className="craft-footer"><a href="/">3D Craft</a><nav aria-label="Support and legal">{links.map(([url, label]) => <a key={url} href={url}>{label}</a>)}</nav><span>© {new Date().getFullYear()} Jiawen Zhu</span></footer>;
type Section = [string, React.ReactNode];
const mail = <a href={`mailto:${email}`}>{email}</a>;
const pages: Record<string, { title: string; intro: string; sections: Section[] }> = {
  '/privacy': { title: 'Your ideas. Your privacy.', intro: 'Privacy policy for 3D Craft, operated by Jiawen Zhu. Effective September 12, 2026.', sections: [
    ['What we process', 'We process the account details you provide, account or session identifiers, uploaded reference photos, text prompts and conversations, generated images and 3D files, and information needed to track generation jobs and credit usage. Support requests include the information you send us. Hosting and service providers may process connection information such as IP addresses and operational logs.'],
    ['Why we use it', 'We use this information to sign you in, generate and retrieve your creations, process your chosen AI requests, maintain credit balances, troubleshoot errors, protect the service, and answer support requests. Avoid uploading sensitive personal information or images of people without permission.'],
    ['AI and service providers', <>Your prompts and reference images are sent to the provider selected for the requested generation. Depending on the feature, this may include Google Gemini, OpenAI through an optional connected account, and fal.ai or its model providers. Google Firebase supports web authentication, storage of app records, and hosting. Provider processing is also governed by their terms and privacy policies. We do not promise that all providers exclude all data from training; review the selected provider’s terms before sending confidential material. See <a href="https://policies.google.com/privacy">Google</a>, <a href="https://openai.com/policies/privacy-policy/">OpenAI</a>, and <a href="https://fal.ai/privacy">fal.ai</a>.</>],
    ['Phone support', <>Our optional AI phone support uses Vapi and its speech and AI providers to process your voice and call information so the assistant can respond. We have disabled audio recording, stored transcripts and call logging in our assistant configuration; providers may still process operational metadata under their own policies. You can contact us by email instead. See <a href="https://vapi.ai/privacy">Vapi’s privacy policy</a>.</>],
    ['Purchases and sharing', 'Apple handles App Store payment details. Purchase identifiers, entitlement status and credit records may be processed to deliver purchases, including through RevenueCat when enabled. We do not receive your complete payment card details from Apple. Exporting or sending a creation to another app shares the files and prompt you select with that destination. The destination’s privacy terms apply. Private creations are separate from our curated example gallery.'],
    ['Storage and retention', 'Account and creation records may remain stored while your account or saved creations remain active. Local caches may remain on your device. We have not implemented automatic expiry for all uploaded files and generation records. You can request deletion using the contact below. Some transaction, security or legally required records may need to be retained after a request; we will explain relevant exceptions when responding. Deletion of our copies does not remove files you exported or independently shared with others.'],
    ['Your choices', <>You can stop uploading content, disconnect an optional connected account, and request access, correction or deletion of your information. Contact {mail} from your account email if possible. We may request proportionate information to verify ownership. See <a href="/delete-account">data and account deletion</a>. We do not sell your personal information or use it for targeted advertising.</>],
    ['Device storage and security', 'The web app uses browser storage and Firebase authentication to maintain sessions and preferences. We use service access controls and encrypted network connections where supported. No storage or transmission method is completely secure.'],
    ['Children and updates', <>3D Craft is a general creative tool, not a service specifically directed to children. A parent or guardian who believes a child has provided personal information should contact {mail}. This policy may change as the service changes; the effective date identifies the current version. Questions and privacy requests go to {mail}.</>],
  ]},
  '/terms': { title: 'Create with confidence.', intro: 'Terms of use for 3D Craft. Effective September 12, 2026.', sections: [
    ['Using 3D Craft', '3D Craft is operated by Jiawen Zhu and helps you create concept images and 3D assets from text and reference images. By using the service, you agree to these terms. You must be legally able to agree to these terms, or use the service with appropriate parent or guardian authorization where permitted. Keep your account secure and use accurate account information.'],
    ['Your content and rights', 'You retain rights you already have in your uploads. You give us permission to process, store and transmit that content as needed to deliver your requested features. Upload only material you have permission to use, including the likeness of other people. AI output may resemble other works, may not be unique, and may not qualify for copyright protection. We do not guarantee ownership, exclusivity or commercial clearance. Review output and applicable model-provider terms before publishing or selling it.'],
    ['Responsible use', <>Do not use the service for illegal activity, exploitation of children, nonconsensual sexual imagery, harassment, fraud, hate, or infringement of others’ rights. Do not attempt to bypass access controls or provider safeguards. Report concerns to {mail}. See our <a href="/policy">usage policy</a>.</>],
    ['Generation and availability', 'AI results can be inaccurate or incomplete. Images and meshes may require editing, optimization or review before use in a game or commercial product. Generation depends on model availability and connected services; timing and results are not guaranteed. External game builders operate under their own terms.'],
    ['Subscriptions and credits', <>Where purchases are available, the purchase screen shows the applicable price, period, included credits and renewal terms before you confirm. Weekly and monthly subscriptions renew through Apple unless canceled. Credits are usage units, not cash or a transferable currency. Model choice, image count and additional operations affect consumption; examples of possible creations are estimates. See <a href="/policy">billing and refunds</a>.</>],
    ['Ending use and responsibility', 'You may stop using the service and request account deletion. We may restrict use that violates these terms or threatens service security. To the extent allowed by law, the service is provided as available without a guarantee of uninterrupted availability or a particular creative result. Nothing in these terms removes mandatory consumer rights or liability that cannot lawfully be excluded.'],
    ['Apple license and contact', <>The iOS app also uses <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple’s Standard End User License Agreement</a>. Questions about these terms can be sent to {mail}. Material updates will be reflected in the effective date and communicated where required.</>],
  ]},
  '/policy': { title: 'Clear rules. Clear costs.', intro: 'Usage, credits, subscriptions and refunds for 3D Craft.', sections: [
    ['Creative use', 'Create characters, props and environments using content you have rights to use. Do not upload illegal content, child exploitation material, nonconsensual sexual content, malware, threats or material that infringes another person’s rights. These rules do not imply that every unsafe generation is automatically detected.'],
    ['Credits and generation estimates', 'Generation costs vary with the selected model, image count, chat usage and additional operations. Our pricing model includes a 15% service fee on combined provider costs. Review the displayed quote before confirming. A creation count shown with a plan is an estimate, not a guarantee or a separate entitlement. Purchased credits are not cash and cannot be withdrawn or transferred.'],
    ['Weekly and monthly subscriptions', 'Available plans and localized prices are shown in the App Store purchase sheet. A weekly plan renews weekly and a monthly plan renews monthly unless canceled. Credits included in a subscription are granted following a successful purchase or renewal; purchased unused credits do not expire. No yearly plan is offered. Features and purchases may remain unavailable during pre-release testing.'],
    ['Manage or cancel', <>On iPhone or iPad, open Settings → your name → Subscriptions → 3D Craft. Cancel at least 24 hours before the current period ends to avoid the next renewal. Cancellation stops future renewals; it does not by itself request a refund or delete your account. You can also use <a href="https://apps.apple.com/account/subscriptions">Apple’s subscription management page</a>.</>],
    ['Refunds and failed jobs', <>For App Store purchases, request a refund through <a href="https://reportaproblem.apple.com/">Apple’s Report a Problem</a>; Apple determines eligibility. If a generation fails or a credit balance looks wrong, contact {mail} with the job identifier, approximate time and purchase receipt identifier if relevant. We will investigate the charge. Do not send full payment card details, passwords or API keys.</>],
    ['Report a problem', <>For unsafe output, intellectual-property concerns or other abuse, email {mail} with enough detail to locate the material. We review reports and may remove content or restrict abusive accounts. Privacy requests are covered by our <a href="/privacy">privacy policy</a>.</>],
  ]},
  '/contact': { title: 'A human behind your studio.', intro: 'Help with creations, accounts, purchases, or privacy. Contact the developer directly.', sections: [
    ['Contact Jiawen Zhu', <><a className="craft-contact" href={`mailto:${email}`}><Mail size={22}/>{email}</a><p>For the fastest investigation, include your app version, device model, what happened, and a job identifier or screenshot when helpful. Never send passwords, sign-in codes or secret keys.</p></>],
    ['Call 3D Craft', <><a className="craft-contact" href="tel:+17472811202"><Phone size={22}/>+1 (747) 281-1202</a><p>An AI assistant can help with general product questions. For account-specific help, refunds or privacy requests, email {mail}. Please do not share passwords, verification codes or payment details on a call. Carrier charges may apply.</p></>],
    ['Generation or missing credits', 'Include the approximate generation time, selected model and job identifier. If possible, keep the original error message so we can investigate.'],
    ['Subscriptions and refunds', <>Manage Apple subscriptions in your device Settings. For a purchase refund, use <a href="https://reportaproblem.apple.com/">Apple’s refund request page</a>. See <a href="/policy">our billing policy</a> for details.</>],
    ['Privacy and deletion', <>Email the same support address for data access, correction, account deletion or privacy questions. Our <a href="/delete-account">deletion page</a> explains what to include.</>],
  ]},
  '/delete-account': { title: 'Your data, your choice.', intro: 'Request deletion of your 3D Craft account and associated content.', sections: [
    ['Send a deletion request', <><a className="craft-contact" href={`mailto:${email}?subject=3D%20Craft%20account%20and%20data%20deletion`}>Request account and data deletion</a><p>Send your request from the email associated with your account when possible. If you used a guest session, include any available account/session or job identifier. State whether you want the whole account or specific creations deleted. We may need to verify that you own the account before acting.</p></>],
    ['What happens next', 'We will review your request and explain the relevant records and any information needed to locate them. Some transaction or security records may be retained where required by law or to handle disputes. Exported files and copies shared with third parties are not deleted by removing your account.'],
    ['Cancel subscriptions separately', 'Deleting an account or uninstalling the app does not automatically cancel an Apple subscription. Cancel it in Settings → your name → Subscriptions. Keep any creations you wish to export before requesting deletion.'],
  ]},
};
export const isLegalPath = (path: string) => path.replace(/\/$/, '') in pages || path === '/support';
export function LegalPage() {
  const path = window.location.pathname.replace(/\/$/, '');
  const page = pages[path === '/support' ? '/contact' : path];
  React.useEffect(() => { document.title = `${page.title} — 3D Craft`; }, [page.title]);
  return <div className="craft-legal"><header><a href="/" className="craft-brand"><Box/>3D Craft</a><a href="/"><ArrowLeft size={16}/> Back to studio</a></header><main><p className="craft-eyebrow">3D CRAFT · SUPPORT & INFORMATION</p><h1>{page.title}</h1><p className="craft-intro">{page.intro}</p><nav className="craft-toc" aria-label="On this page">{page.sections.map(([title], i) => <a key={title} href={`#section-${i}`}>{title}</a>)}</nav>{page.sections.map(([title, body], i) => <section key={title} id={`section-${i}`}><span className="craft-section-number">{String(i + 1).padStart(2, '0')}</span><div><h2>{title}</h2><div className="craft-body">{body}</div></div></section>)}</main><LegalFooter/></div>;
}
